// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCySks36F5jdXExgwhVnp_qnOtz4QxD1mA',
    appId: '1:106211637862:web:1d5001ce0cf3c7be3a4ba7',
    messagingSenderId: '106211637862',
    projectId: 'vverify-c6478',
    authDomain: 'vverify-c6478.firebaseapp.com',
    storageBucket: 'vverify-c6478.firebasestorage.app',
    measurementId: 'G-BP137CJCSC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAV2dJD8dXM0iUQ78Fj58f0F5aO53W8Ui4',
    appId: '1:106211637862:android:80aabf67305588813a4ba7',
    messagingSenderId: '106211637862',
    projectId: 'vverify-c6478',
    storageBucket: 'vverify-c6478.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClFBH8nsPg-Zo3vWmEX-mEryjd6VOaJYc',
    appId: '1:106211637862:ios:d5e915cf63d7f7a53a4ba7',
    messagingSenderId: '106211637862',
    projectId: 'vverify-c6478',
    storageBucket: 'vverify-c6478.firebasestorage.app',
    iosBundleId: 'com.example.vVerify',
  );
}
